##### Get products list
GET http://localhost:8080/DAE_Proj_war_exploded/api/products
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE1NzU1ODE1NTJ9.X-gpyEgVMMiBxE4-1oskSwZGSIRwCME5DNESZAQRslVVgFFEGhuxfHzwIIKSMFgDO2zN883sKMbsJJ0oM_sHvgTVmVNaJI7f1mps5Poa-pImRr2Vb4bcld6XdOR-lOm3RVWwcen0_05aMY_MZ8kRf-ugTo8zEjwl_Jdux6jWCM2_CY4s0j2wX0p4gmE-QaEWSt_zSB_M1hPymSIhVY6AE0ULFUfc5zSDArzpZOwq_R9CK1jMtQGvudwp1zEmAwyG_zhDNFDR983yX_reMduFNVMTcjUDQxbiNJxNF9jPh91X8Ul_EVk_3wOC3bCyIPXSyMQguhN0DP3lLVo-exlHOw
###

#####
GET http://localhost:8080/DAE_Proj_war_exploded/api/products/0
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE1NzU1ODE1NTJ9.X-gpyEgVMMiBxE4-1oskSwZGSIRwCME5DNESZAQRslVVgFFEGhuxfHzwIIKSMFgDO2zN883sKMbsJJ0oM_sHvgTVmVNaJI7f1mps5Poa-pImRr2Vb4bcld6XdOR-lOm3RVWwcen0_05aMY_MZ8kRf-ugTo8zEjwl_Jdux6jWCM2_CY4s0j2wX0p4gmE-QaEWSt_zSB_M1hPymSIhVY6AE0ULFUfc5zSDArzpZOwq_R9CK1jMtQGvudwp1zEmAwyG_zhDNFDR983yX_reMduFNVMTcjUDQxbiNJxNF9jPh91X8Ul_EVk_3wOC3bCyIPXSyMQguhN0DP3lLVo-exlHOw
###

#####
POST http://localhost:8080/DAE_Proj_war_exploded/api/products
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE1NzU1ODY2Mzl9.d5KD8qkp--VtREauxz9uO38kwk93dIimbgr5v1-fTrQ3pQPaKawBfiQKsUN1lys-srzLZ-3Sx2OFYw2gNVR_tT3-pPD19p4xjcmkOZGvauK6eez1-tnqGLuCNjaRklb76oVCbfeiz0tdXRt7Q_Kb5O9CJz48rEZi_DwBg9IONk244Bay5zL6XMimWC1IPNqGQZcM6Is_o0NtIsLHkRZjdY9-UdKf5xsTMTEReDHUaJjwXyfCde8YM9VRRqYzB1zrngqCuDp5neTs5cm45dClI3kT4vJx-4ynR449-tlIbe5dDnmsuJtniOwmYfVoVB1jfw6__SJZ9rArjJt4GbQn3w

{
  "category": "Artigo Desportivo",
  "description": "teste",
  "value": 666
}

###

